spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto : update
    show-sql : true
  datasource:
    url: jdbc:postgresql://localhost:5432/tourmate_test
    username: postgres
    password: root


  #spring:
  #  jpa:
  #    properties:
  #      hibernate:
  #        dialect: org.hibernate.dialect.PostgreSQLDialect
  #    hibernate:
  #      ddl-auto : update
  #    show-sql : true
  #  datasource:
  #    url: jdbc:postgresql://workerdb.cfuos80wqf3n.eu-central-1.rds.amazonaws.com:5432/tourmate_test
  #    username: postgres
  #    password: yusif20033


  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 7MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: yusifjz@code.edu.az
    password: xpdskzcszxuauvzh
    properties:
      mail:
        smpt:
          auth: true
        starttls:
          enable: true

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
  bucket:
    name: birseyyoxlayiram
    branch-profile-name: branchprofile
    user-profile-name: tourmateuserprofile
    management-profile-name: managementprofile
    rooms-image: tourmaterooms
    branch-profile-link: https://branchprofile.s3.eu-central-1.amazonaws.com/
    user-profile-link: https://tourmateuserprofile.s3.eu-central-1.amazonaws.com/
    management-profile-link: https://managementprofile.s3.eu-central-1.amazonaws.com/
    name-link: https://tourmate.s3.eu-central-1.amazonaws.com/
    rooms-link: https://tourmaterooms.s3.eu-central-1.amazonaws.com/


cloud:
  aws:
    credentials:
      access-key: AKIAXMC7GIB5FDEOBBSK
      secret-key: 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
      region:
        static: eu-central-1
      stack:
        auto: false
